INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YKL015W','PUT3','Transcriptional activator');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGL252C','RTG2','Sensor of mitochondrial dysfunction');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YHL027W','RIM101','Cys2His2 zinc-finger transcriptional repressor');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YJL006C','CTK2','Beta subunit of C-terminal domain kinase I (CTDK-I)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YMR233W','TRI1','Non-essential sumoylated protein of unknown function');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YAL021C','CCR4','Component of the CCR4-NOT transcriptional complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YKL139W','CTK1','Catalytic (alpha) subunit of C-terminal domain kinase I (CTDK-I)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDL007W','RPT2','ATPase of the 19S regulatory particle of the 26S proteasome');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YKL145W','RPT1','ATPase of the 19S regulatory particle of the 26S proteasome');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YOR117W','RPT5','ATPase of the 19S regulatory particle of the 26S proteasome');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR394W','RPT3','ATPase of the 19S regulatory particle of the 26S proteasome');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YKL018W','SWD2','Subunit of the COMPASS (Set1C) histone H3K4 methyltransferase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YNL229C','URE2','Nitrogen catabolite repression transcriptional regulator');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLR277C','YSH1','Endoribonuclease');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR103W','SIF2','WD40 repeat-containing subunit of Set3C histone deacetylase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YEL037C','RAD23','Protein with ubiquitin-like N terminus');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGR040W','KSS1','Mitogen-activated protein kinase (MAPK)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER162C','RAD4','Protein that recognizes and binds damaged DNA (with Rad23p) during NER');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YPL031C','PHO85','Cyclin-dependent kinase');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER174C','GRX4','Glutathione-dependent oxidoreductase');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR098C','GRX3','Glutathione-dependent oxidoreductase');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR381W','YRA1','Nuclear polyadenylated RNA-binding protein');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR159W','SAC3','mRNA export factor');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YHR071W','PCL5','Cyclin');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YPR158W','CUR1','Sorting factor, central regulator of spatial protein quality control');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGR258C','RAD2','Single-stranded DNA endonuclease');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLL035W','GRC3','Polynucleotide kinase present on rDNA');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLR011W','LOT6','FMN-dependent NAD(P)H:quinone reductase');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YPL181W','CTI6','Component of the Rpd3L histone deacetylase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER177W','BMH1','14-3-3 protein, major isoform');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER120W','SCS2','Integral ER membrane protein, regulates phospholipid metabolism');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YOR344C','TYE7','Serine-rich protein that contains a bHLH DNA binding motif');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YMR168C','CEP3','Essential kinetochore protein');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR195W','REF2','RNA-binding protein');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR404C','RPB7','RNA polymerase II subunit B16');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLR039C','RIC1','Protein involved in retrograde transport to the cis-Golgi network');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLR274W','MCM5','Component of the Mcm2-7 hexameric helicase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGL190C','CDC55','Non-essential regulatory subunit B of protein phosphatase 2A (PP2A)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER133W','GLC7','Type 1 S/T protein phosphatase (PP1) catalytic subunit');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR143C','SUP45','Polypeptide release factor (eRF1) in translation termination');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDL166C','FAP7','Essential NTPase required for small ribosome subunit synthesis');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGR006W','PRP18','Splicing factor and component of snRNP U5');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YJL140W','RPB4','RNA polymerase II subunit B32');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YEL032W','MCM3','Protein involved in DNA replication');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR202W','MCM7','Component of the Mcm2-7 hexameric helicase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YLR103C','CDC45','DNA replication initiation factor');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR088C','POL30','Proliferating cell nuclear antigen (PCNA)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YGL241W','KAP114','Karyopherin, responsible for nuclear import of specific proteins');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YKL054C','DEF1','RNAPII degradation factor');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YNL159C','ASI2','Subunit of the nuclear inner membrane Asi ubiquitin ligase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YPL125W','KAP120','Karyopherin responsible for the nuclear import of Rpf1p');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR017C','KAP104','Transportin or cytosolic karyopherin beta 2');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YER107C','GLE2','RNA export factor associated with the nuclear pore complex (NPC)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YMR119W','ASI1','Subunit of the nuclear inner membrane Asi ubiquitin ligase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YNL008C','ASI3','Subunit of the nuclear inner membrane Asi ubiquitin ligase complex');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YOR257W','CDC31','Calcium-binding component of the spindle pole body (SPB) half-bridge');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YBR109C','CMD1','Calmodulin');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YDR180W','SCC2','Subunit of cohesin loading factor (Scc2p-Scc4p)');
INSERT INTO regulome_genes (regulome_id, locus_name, gene_name, note) values ('19','YHR030C','SLT2','Serine/threonine MAP kinase');
